import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import {fixture,root,account,user,slice}from'./helpers/e8-db-fixture.mjs';
async function setup({partial=false}={}){const f=await fixture();await f.db.exec(`
 alter table e8_monitor_profiles add column max_quote_age_ms int default 15000;
 create table e8_instrument_evidence(id bigint generated always as identity,account_id bigint,symbol text,lot_size numeric,quote_currency text,observed_at timestamptz,details jsonb);
 create table cost_symbol_model(symbol text,e8_commission_per_lot numeric,note text,ipfx_commission_per_lot numeric default 6,contract numeric default 100000,quote_ccy text default 'USD');
 create table cost_samples(symbol text,role text,account_id bigint,spread numeric,ipfx_spread numeric,sampled_at timestamptz default now());
 create table live_quotes(symbol text primary key,bid numeric,ask numeric,received_at timestamptz default now());
 alter table symbol_specs add column commission_per_lot_usd numeric default 6;
 create table ipfx_sim_decision_quotes(audit_id bigint,trade_id uuid,source_row_id uuid,kind text,lots numeric,bid numeric,ask numeric,quote_ts timestamptz,server_ts timestamptz);
 create view ipfx_sim_decision_results as select '${root}'::uuid trade_id,1::numeric selected_gross_usd;
 create function ab_brain_live_activity(uuid)returns jsonb language sql as $$select to_jsonb(x)from(select r.trade_id,d.status decision_status,d.selected_gross_usd decision_gross_usd from e8_sim_trade_results r left join (select trade_id,'test' status,selected_gross_usd from ipfx_sim_decision_results)d using(trade_id)where r.person_id=$1)x$$;
 insert into cost_symbol_model(symbol,e8_commission_per_lot,note) values('EURUSD',5.5,'configured forex estimate');
 insert into e8_instrument_evidence(account_id,symbol,lot_size,quote_currency,observed_at,details) values(3,'EURUSD',200000,'USD',now()-interval '200 seconds','{"minLot":0.01,"maxLot":50,"lotStep":0.01,"tickSize":[{"tickSize":0.00001}]}');
 `);await f.db.exec(fs.readFileSync(new URL('../supabase/migrations/20261008234000_sim_accuracy_breakdown.sql',import.meta.url),'utf8'));
 await f.open();
 if(partial)await f.db.exec(`update trades set volume=.01 where id='${root}';insert into trades(id,parent_trade_id,account_id,user_id,symbol,side,volume,status,open_price,opened_at,closed_at,commission,close_reason)select '${slice}',id,account_id,user_id,symbol,side,.01,'closed',open_price,opened_at,now()-interval '40 seconds',.06,'partial' from trades where id='${root}';`);
 await f.db.exec(`update trades set status='closed',closed_at=now()-interval '20 seconds',commission=${partial?'.06':'.12'} where id='${root}';
 insert into ipfx_sim_decision_quotes values(1,'${root}','${root}','open',.02,1.1,1.1002,now()-interval '120 seconds',now()-interval '119 seconds'),(2,'${root}','${root}','close',.02,1.099,1.0992,now()-interval '20 seconds',now()-interval '19 seconds');`);
 await f.quote(119,1.1,1.1002);if(partial)await f.quote(39,1.098,1.0982);await f.quote(19,1.099,1.0992);await f.db.query('select e8_sim_tick()');return f;}
const accuracy=async db=>(await db.query('select e8_sim_accuracy($1)a',[root])).rows[0].a;
const close=(actual,expected)=>assert.ok(Math.abs(Number(actual)-expected)<1e-7,`${actual} != ${expected}`);
test('broker contract adjustment, recorded commission and explicit tick scenarios reconcile without claiming executed net',async()=>{const f=await setup();try{const a=await accuracy(f.db);close(a.e8_gross_usd,3.2);close(a.e8_commission_usd,.11);close(a.e8_after_commission_usd,3.09);close(a.ipfx_after_commission_usd,.88);close(a.one_tick_slippage_usd,.08);close(a.one_tick_after_commission_usd,3.01);assert.equal(a.scale_basis,'BROKER_SPEC_OBSERVED_AT_ENTRY');assert.equal(a.net_verified,false);assert.equal(a.net_usd,null);assert.equal(a.events.length,2);assert.ok((await f.db.query('select ab_brain_live_activity($1)a',[user])).rows[0].a.accuracy);await f.db.exec('set role authenticated');await assert.rejects(f.db.query('select e8_sim_accuracy($1)',[root]),/permission denied/);}finally{await f.db.close();}});
test('unknown zero commission stays missing; later specs never become historical proof',async()=>{const f=await setup();try{await f.db.exec("update cost_symbol_model set e8_commission_per_lot=0,note='E8 commission unknown';update e8_instrument_evidence set observed_at=now()");const a=await accuracy(f.db);assert.equal(a.e8_commission_usd,null);assert.equal(a.e8_after_commission_usd,null);assert.equal(a.commission_basis,'UNKNOWN_NOT_ZERO');assert.equal(a.scale_basis,'LATER_SPEC_BACKCAST_ESTIMATE');assert.equal(a.net_verified,false);}finally{await f.db.close();}});
test('out-of-limit size, non-USD conversion and invalid decision timing cannot claim cost-adjusted amounts',async()=>{const f=await setup();try{await f.db.exec(`update e8_instrument_evidence set details='{"minLot":0.01,"maxLot":0.01,"lotStep":0.01}';`);assert.equal((await accuracy(f.db)).e8_gross_usd,null);await f.db.exec("update e8_instrument_evidence set quote_currency='JPY';update ipfx_sim_decision_quotes set quote_ts=server_ts+interval '1 second'");const a=await accuracy(f.db);assert.equal(a.e8_gross_usd,null);assert.equal(a.decision_timing_valid,false);assert.equal(a.ipfx_after_commission_usd,null);}finally{await f.db.close();}});
test('partial exits allocate commission once and keep the full exited quantity and price evidence',async()=>{const f=await setup({partial:true});try{const a=await accuracy(f.db);close(a.e8_gross_usd,5.2);close(a.e8_commission_usd,.11);close(a.ipfx_commission_usd,.12);close(a.exited_lots,.02);assert.equal(a.events.length,3);close(a.one_tick_slippage_usd,.08);}finally{await f.db.close();}});
test('all-in comparison uses separate venue sizes and withholds missing or mixed reference evidence',async()=>{const f=await setup();try{await f.db.exec("insert into cost_samples(symbol,role,account_id,spread,ipfx_spread)values('EURUSD','monitor',3,.00001,.00001)");let r=(await f.db.query('select * from cost_allin(24)')).rows[0];close(r.e8_usd,7.5);close(r.ipfx_usd,7);await f.db.exec("insert into cost_samples(symbol,role,account_id,spread,ipfx_spread)values('EURUSD','monitor',4,.00001,.00001)");r=(await f.db.query('select * from cost_allin(24)')).rows[0];assert.equal(r.e8_usd,null);assert.equal(r.ratio,null);}finally{await f.db.close();}});
