-- CME futures for the Futures Challenge. contract_size = dollars per 1.00 of price (matches trading-engine INSTRUMENTS).
-- Commission is per contract, charged round-turn on close: US$4 full-size, US$1 micro.
begin;
alter table public.symbol_specs drop constraint if exists symbol_specs_asset_class_check;
alter table public.symbol_specs add constraint symbol_specs_asset_class_check check (asset_class = any (array['forex','metal','index','crypto','future']));
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('ES','E-mini S&P 500','future',2,50,'USD',1,20,1,0.25,1.0,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('MES','Micro E-mini S&P 500','future',2,5,'USD',1,100,1,0.25,1.0,0.3,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('NQ','E-mini Nasdaq-100','future',2,20,'USD',1,20,1,0.5,2.0,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('MNQ','Micro E-mini Nasdaq-100','future',2,2,'USD',1,100,1,0.5,2.0,0.3,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('YM','E-mini Dow','future',0,5,'USD',1,20,1,2,8,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('MYM','Micro E-mini Dow','future',0,0.5,'USD',1,100,1,2,8,0.3,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('RTY','E-mini Russell 2000','future',1,50,'USD',1,20,1,0.2,0.8,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('M2K','Micro E-mini Russell 2000','future',1,5,'USD',1,100,1,0.2,0.8,0.3,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('CL','Crude Oil WTI','future',2,1000,'USD',1,20,1,0.02,0.08,0.5,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('MCL','Micro Crude Oil','future',2,100,'USD',1,100,1,0.02,0.08,0.5,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('GC','Gold Futures','future',1,100,'USD',1,20,1,0.2,0.8,0.5,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('MGC','Micro Gold','future',1,10,'USD',1,100,1,0.2,0.8,0.5,'CME Globex',true,1) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('NG','Natural Gas','future',3,10000,'USD',1,20,1,0.004,0.016,0.5,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('ZB','US Treasury Bond (30Y)','future',3,1000,'USD',1,20,1,0.03125,0.125,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
insert into public.symbol_specs(symbol,display_name,asset_class,digits,contract_size,quote_currency,min_volume,max_volume,volume_step,base_spread,max_spread,slippage_bps,session_hours,enabled,commission_per_lot_usd) values('ZN','US Treasury Note (10Y)','future',3,1000,'USD',1,20,1,0.015625,0.0625,0.3,'CME Globex',true,4) on conflict (symbol) do nothing;
commit;
